name: Translate Victoria 3 Localization

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install deep-translator

    - name: Run Translation Script
      run: |
        python translate.py

    - name: Create Release Zip Artifact
      run: |
        cd fa_files
        zip -r ../victoria3_farsi_translation.zip .

    - name: Upload Translation Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Victoria3-Farsi-Translation
        path: victoria3_farsi_translation.zip
